{
  "use_super4pcs": false,
  "use_fpfh": true,
  "use_icp": false,
  
  "process" :
  {
    "downsample_leaf_size": 0.025,
    "normal_SearchRadius": 0.05,
    "features_SearchRadius": 0.05
  },

  "fpfh" :
  {
    "MaximumIterations": 100000,
    "NumberOfSamples": 3,
    "CorrespondenceRandomness": 5,
    "SimilarityThreshold": 0.85,
    "MaxCorrespondenceDistance": 0.0125,
    "InlierFraction": 0.25  
  },

  "super4pcs" :
  {
    "overlap": 0.1,
    "delta": 0.0005,
    "samples": 50000
  },

  "icp" :
  {
    "MaximumIterations": 1000,
    "EuclideanFitnessEpsilon": 0.1,
    "TransformationEpsilon": 0.1,
    "MaxCorrespondenceDistance": 0.05, 
  }
}
