{
  "super4pcs" :
  {
    "overlap": 0.6,                  # Expected overlapping point fraction
    "delta": 0.005,                   # Point error after transformation estimation
    "samples": 200                    # number of samples for alignment, Super4PCS has linear time complexity wrt samples - documentation suggests 200 is generally sufficient
  }
}
